### ISSUE TITLE
The plugin throws an error with non-ASCII characters

### ISSUE THREAD

**Issue by Andre-J** [rduivenvoorde/xytools#3]
I have a shapefile with utf-8 encoding which fails to get exported with the xytools. The name field of one object contains a non-ASCII chraracter, which seems to be evil:

Traceback (most recent call last):
  File "C:/Users/Joost/.qgis2/python/plugins\xytools\xytools.py", line 301, in excelSave
    xlw.writeAttributeRow(rowNr, values)
  File "C:/Users/Joost/.qgis2/python/plugins\xytools\providers\excel.py", line 51, in writeAttributeRow
    cell = str(cell)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 1: ordinal not in range(128)

**Comment by lobobruno** [comment]
Same issue here!
